# syntax=docker/dockerfile:1
ARG RUBY_VERSION=3.3.10
FROM docker.io/library/ruby:${RUBY_VERSION}-slim

WORKDIR /rails

# 開発で必要なもの一式（make含む）
RUN apt-get update -qq && \
  apt-get install --no-install-recommends -y \
  build-essential \
  git \
  curl \
  libpq-dev \
  libyaml-dev \
  pkg-config \
  postgresql-client \
  libvips \
  && rm -rf /var/lib/apt/lists /var/cache/apt/archives

# 開発用（frozen/without を強制しない）
ENV RAILS_ENV="development" \
  BUNDLE_PATH="/usr/local/bundle"

# 先にGemだけコピーしてbundle（キャッシュが効く）
COPY Gemfile Gemfile.lock ./
RUN bundle install

# アプリコード
COPY . .

ENTRYPOINT ["/rails/bin/docker-entrypoint"]

EXPOSE 3000
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0", "-p", "3000"]
